### ISSUE TITLE
This plugin does not seem to work under windows

### ISSUE THREAD

**Issue by danships** [KELiON/cerebro-ip#1]
I have installed this plugin on the 0.2.1 release on Windows. But when I type `ip` no information shows up.

**Comment by KELiON** [comment]
@matueranet it used Linux-only bash commands, now I published version 0.1.2. Can you try it? Should be cross-platform

**Comment by danships** [comment]
Thanks it works now. It shows my internal and external IP.

I did have to uninstall and reinstall it however. At first Cerebro did not detect there was an update of the plugin. I closed it and restarted that. Then it showed version 0.2.1 and that it was installed, but it still did not work. Maybe only the displaying of the version was updated, and not the plugin itself?

**Comment by KELiON** [comment]
Yes, there is a small issue with plugins versioning now. Cerebro always shows latest available version, but show "installed" even if installed another version. I'm work on it + I want to add autoupdate for plugins. 

Thanks for report!
